Repository asAshutosh/HacktoberFest2021-Accepted, pull requests merged in 2021-10, with the labels that each got.

#14 Dfs code committed by Shubhi
  DFS.cpp
Labels: hacktoberfest

#16 Pls Accept
  11Index.html
  yes.html
Labels: hacktoberfest, hacktoberfest2021

#17 BFS.py
  bfs.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#19 factorial.c
  LinkedList.cpp
  factorial.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#18 Added Google Clone Using HTML
  html/google_clone.html
  html/images/google.png
  html/images/mic.png
  html/images/search.png
  html/images/user.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2021
